version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_management_db
  
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - food-ordering-network
    restart: always

  food-ordering-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-ordering-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/restaurant_management_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9000:9000"
    networks:
      - food-ordering-network
    restart: always

volumes:
  mysql-data:

networks:
  food-ordering-network:
    driver: bridge
